#ifndef token_h
#define token_h

#include <stddef.h>
#include <stdint.h>
typedef enum TokenType {
  TOKEN_HASH,
  TOKEN_HASH2,
  TOKEN_HASH3,
  TOKEN_HASH4,
  TOKEN_HASH5,
  TOKEN_HASH6,
  TOKEN_EQ,
  TOKEN_DOT,
  TOKEN_STAR,
  TOKEN_STAR2,
  TOKEN_STAR3,
  TOKEN_MINUS,
  TOKEN_MINUS2,
  TOKEN_MINUS3,
  TOKEN_UNDERSCORE,
  TOKEN_UNDERSCORE2,
  TOKEN_UNDERSCORE3,
  TOKEN_PLUS,
  TOKEN_PLUS2,
  TOKEN_PLUS3,
  TOKEN_TICK,
  TOKEN_TICK2,
  TOKEN_TICK3,
  TOKEN_TEXT,
  TOKEN_NUM,
  TOKEN_LBRACKET,
  TOKEN_RBRACKET,
  TOKEN_LPAREN,
  TOKEN_RPAREN,
  TOKEN_LT,
  TOKEN_GT,
  TOKEN_BANG,
  TOKEN_BACKSLASH,
  TOKEN_LINE_ENDING,
  TOKEN_WHITESPACE,
  TOKEN_EOF,
  TOKEN_ERROR
} TokenType;

typedef struct Token {
  const char *start;
  size_t length;
  int line;
  TokenType type;
} Token;

#endif
